#!/usr/bin/env php

<?php

use Tempcord\Support\TempcordConsoleApplication;
use Tempest\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

try {
    ConsoleApplication::boot(
            name: 'Tempcord',
    )->run();
} catch (\Tempest\Console\ExitCodeWasInvalid $e) {

}
